### ISSUE TITLE
Strange new issue when decompiling (VSIF2VCD copies folders into a tmp folder and then closes before decompiling Scenes.image)

### ISSUE THREAD

**Issue by SuperMario20** [SlawekNowy/vsif2vcd#4] opened 2022-03-29 21:32 UTC
All of the compile errors are gone, but now whenever I try to decompile a scenes.image in any source game directory with all of the correct folders, vsif2vcd sits on a blank screen for a while and then closes. It copies every map file in the folder containing the gameinfo.txt even if it wasn't in the maplist.txt and then copies the scripts folder and scenes folder. It puts them all into a tmp folder outside the directory. Then it closes before it decompiles scenes.image. I tested it with Half-Life 2, Portal, and Team Fortress 2. I tested the old version to be sure it wasn't on my end and when I dragged the folder to the old vsif2vcd it instantly decompiled the scenes.images, albeit gibberish filenames for the TF2 folder. Is there something causing VSIF2VCD to not decompile the scenes.image?

**Comment by MrSoup678** [comment] 2022-03-31 15:47
Check tmp folder ABOVE the directory you gave to VSIF2VCD.

**Comment by SuperMario20** [comment] 2022-03-31 17:34
By above you mean in the parent folder? I did check, it had copied everything and made autogenerated files from the response rules but the only thing in the scenes folder was still the scenes.image, it copied everything but just didn't decompile the scenes.image

**Comment by LittlePlanetCD** [comment] 2022-04-03 03:51
yeah, this is happening to me as well.

all the program does is copy the stuff needed to decompile into a place like Half-life 2/tmp but doesnt actually decompile the scenes.image file.

**Comment by MrSoup678** [comment] 2022-04-04 10:30
I checked the issue. Turns out I accidentally caused 3GB leak just by assuming entity lump was compressed (that would be the decompressed buffer),which was not the case for HL2, for EVERY MAP. That massive leak was fixed, alongside with other minor leaks I encountered (Note to self: do NOT use *new Class(). We're leaking memory left and right with that). Hence 1.0.0 was being removed from Releases and replaced with 1.0.1, which you can now check. That version has logging also.

**Comment by Xenthio** [comment] 2022-06-02 05:28
doesn't seem to be fixed. still no scene files are being produced

**Comment by MrSoup678** [comment] 2022-06-02 05:33
1. What game did you try to extract?

2. Did you redownload the built executable? You might have the leaky old version.

3. What system are you running?

**Comment by Xenthio** [comment] 2022-06-02 05:35
I downloaded the built executable that was released on april 4th, I ran the executable on my half-life 2 install, I'm running Windows 11 64-bit

**Comment by MrSoup678** [comment] 2022-06-11 07:55
Run this executable on cmd or PowerShell. Do you have anything printed to it?

**Comment by kristiker** [comment] 2022-09-17 15:34
`[I] VSIF::ValveScenesImageFile::ValveScenesImageFile: Loading file header of C:\Program Files (x86)\Steam/steamapps/common/Counter-Strike Global Offensive/tmp//scenes/scenes.image
`
but scenes.image is in /csgo/ not in /tmp/

putting scenes.image in tmp loads the pc up but still fails ulitmately

**Comment by MrSoup678** [comment] 2022-09-19 14:37
@kristiker This is beacuse I do not implicitly mount pak01.vpk files, right now. There's no gameinfo indication of doing so.

**Comment by FlaminSarge** [comment] 2022-12-01 05:06
I'm attempting to extract Team Fortress 2's scenes with 1.0.1, and the program appears to quit after `fillWithVCDS()`. It does _not_ reach the log line "Now extracting scene names from maps.", but it does properly copy all map/talker/response/etc files to the `tmp` folder, even extracting them from VPKs when necessary, then executes `fillWithVCDS()`, which logs all the CRCs. After that, no output, program end.

Of note, I don't think TF2 has that many scenes, if any, in its maps; they're all probably in the responses. However, the program should definitely at least have reached the part where it attempts to extract scene names from maps instead of just closing.

**Comment by MrSoup678** [comment] 2022-12-01 10:23
I'm going to download TF2 right now. I have temporarily fixed the issue regarding of Version 3 of VSIF (which was the case in CS:GO).
Maybe TF2 now uses it?
I'm not sure.
And If so, can we reverse engineer this from dedicaated server binaries?

EDIT: NVM VSIF has hot reached version 3 in TF2 I presume given your symptoms. BVCD version bump maybe?

**Comment by MrSoup678** [comment] 2022-12-06 12:59
BVCD did not have a version bump. However I have noticed something odd. One of the scenes has OOB index of a string pool.
Either this is misread, or something has been changed.

**Comment by MrSoup678** [comment] 2022-12-06 13:00
And given we have a list of already present crc list, I would think the latter.

**Comment by MrSoup678** [comment] 2022-12-07 08:40
That would be the case, as I retested HL2 scenes,and they're allright.
Also that OOB index occurred at index scene index 1721. What.

**Comment by MrSoup678** [comment] 2022-12-07 09:39
Ok. We're skipping large part of bvcd structure. Why?

**Comment by MrSoup678** [comment] 2022-12-07 09:42
Ok. Event is parsed properly.

**Comment by MrSoup678** [comment] 2022-12-07 10:47
Hmmm... I don't think I have made any errors regarding to parsing.

**Comment by MrSoup678** [comment] 2022-12-07 15:06
I may miss something however and there is a bug somewhere.

**Comment by FlaminSarge** [comment] 2022-12-09 03:01
I'll attempt to set up a dev environment for this on my end to see what's happening.

**Comment by MrSoup678** [comment] 2022-12-09 12:58
Ok I made an experiment. I grabbed old version from dropbox and used it on TF2's directory. That version went without a hitch.
It seems somewhere I have forgotten something, therefore creating regression.

**Comment by MrSoup678** [comment] 2022-12-09 13:29
However this is not without consequences, as the broken file is empty.

**Comment by MrSoup678** [comment] 2022-12-09 13:43
Additionally debugging the C version reveals that it also does not like OOB string entry.

**Comment by MrSoup678** [comment] 2022-12-09 13:47
"jackhammer_rodeo_loop" - One of the strings that succesfully was pointed at. This would point to "Jumping Jack" taunt.

**Comment by FlaminSarge** [comment] 2022-12-09 15:43
Running into some trouble setting up dev environment on win10; something's going wrong with either boost libraries' installation or vcpkg install in general. Unsure what's up.

**Comment by MrSoup678** [comment] 2022-12-22 12:26
I have just converted the project to use vcpkg submodule. Try that now.

**Comment by LittlePlanetCD** [comment] 2023-01-20 04:20
i cant seem to actually get the program to build, it's uh... failing to get certain packages? mentions msys2 and 404s

**Comment by LittlePlanetCD** [comment] 2023-01-20 04:26
```Error: Failed to download from mirror set:
https://repo.msys2.org/mingw/i686/mingw-w64-i686-pkg-config-0.29.2-2-any.pkg.tar.zst: failed: status code 404

https://www2.futureware.at/~nickoe/msys2-mirror/mingw/i686/mingw-w64-i686-pkg-config-0.29.2-2-any.pkg.tar.zst: failed: status code 404

https://mirror.yandex.ru/mirrors/msys2/mingw/i686/mingw-w64-i686-pkg-config-0.29.2-2-any.pkg.tar.zst: failed: status code 404

https://mirrors.tuna.tsinghua.edu.cn/msys2/mingw/i686/mingw-w64-i686-pkg-config-0.29.2-2-any.pkg.tar.zst: failed: status code 404

https://mirrors.ustc.edu.cn/msys2/mingw/i686/mingw-w64-i686-pkg-config-0.29.2-2-any.pkg.tar.zst: failed: status code 404

https://mirror.bit.edu.cn/msys2/mingw/i686/mingw-w64-i686-pkg-config-0.29.2-2-any.pkg.tar.zst: WinHttpSendRequest() failed: 12007

https://mirror.selfnet.de/msys2/mingw/i686/mingw-w64-i686-pkg-config-0.29.2-2-any.pkg.tar.zst: failed: status code 404

https://mirrors.sjtug.sjtu.edu.cn/msys2/mingw/i686/mingw-w64-i686-pkg-config-0.29.2-2-any.pkg.tar.zst: failed: status code 404

**Comment by FlaminSarge** [comment] 2023-01-21 02:04
I have my dev environment set up.

I've pushed several commits to my fork that handles issues I've found:
https://github.com/SlawekNowy/vsif2vcd/compare/master...FlaminSarge:vsif2vcd:master

A few more things I have yet to try to fix:
* `scripts/items/items_game.txt` also contains scene names that should be extracted
* `-nomaps` flag to avoid copying/parsing maps; some games don't have any responses in maps and it would save a lot of time to be able to specify this as a startup param
* I'm sure there's more case-insensitivity handling necessary in `response_system.cpp`
* Need to implement loading from VPKs under the SDK2013 VPK system (e.g. TF2's `tf2_misc_dir.vpk`)
* Duplicate search paths aren't handled, currently, so duplicate work sometimes gets done

(I'm now wondering if it might be better to continue https://github.com/SlawekNowy/vsif2vcd_cs, given the slightly better package support for Valve filetypes there).

**Comment by MrSoup678** [comment] 2023-01-26 15:11
> i cant seem to actually get the program to build, it's uh... failing to get certain packages? mentions msys2 and 404s

I never tested the mingw ecosystem (msys), do hovever update msys via `pacman -Syu`

**Comment by MrSoup678** [comment] 2023-01-26 15:14
> -nomaps flag to avoid copying/parsing maps; some games don't have any responses in maps and it would save a lot of time to be able to specify this as a startup param

either that or checking if we have muiltiplayer only game in gameinfo parser.

> Need to implement loading from VPKs under the SDK2013 VPK system (e.g. TF2's tf2_misc_dir.vpk)

 That's the first thing I implemented in fact. Anything using Orange Box, or SDK 2013 should work seamlessly.

> Duplicate search paths aren't handled, currently, so duplicate work sometimes gets done

Yea I agree with that one.

**Comment by FlaminSarge** [comment] 2023-01-26 19:58
I'm not seeing the app attempt to unpack files from the tf2 vpk search paths, so something doesn't seem to be working correctly on that. Will try to take a look at what's going on.

**Comment by LittlePlanetCD** [comment] 2023-01-26 21:30
> > i cant seem to actually get the program to build, it's uh... failing to get certain packages? mentions msys2 and 404s
> 
> I never tested the mingw ecosystem (msys), do hovever update msys via `pacman -Syu`

that's the thing, iirc i was using *cmake* to do this.

**Comment by FlaminSarge** [comment] 2023-01-31 16:48
> either that or checking if we have muiltiplayer only game in gameinfo parser.
> 
> >

Implemented this in my branch

> That's the first thing I implemented in fact. Anything using Orange Box, or SDK 2013 should work seamlessly.
> 
> >

Unfortunately that's only if it follows the `pak001_dir.vpk` style, not the `tf2_misc_dir.vpk` style; I guess that's not SDK2013 but some other format.

**Comment by SuperMario20** [comment] 2023-01-31 20:03
It's cool to see you continuing to mod both the source engine and
Sourcemod! Best of luck to you with your endeavors!

**Comment by FlaminSarge** [comment] 2023-02-01 07:55
> * `scripts/items/items_game.txt` also contains scene names that should be extracted

I did a quick and dirty impl of this on my branch.


> * Need to implement loading from VPKs under the SDK2013 VPK system (e.g. TF2's `tf2_misc_dir.vpk`)

I fixed what was wrong with this (VPK paths require backslashes when using Find(), apparently).

@SlawekNowy I think my branch is in a state where you can pull it in and try to build, it _should_ mostly work for TF2 now.

**Comment by MrSoup678** [comment] 2023-02-05 17:11
Also I never initialized the filelist at all..
In Linux it worked with forward slashes. Maybe in Windows the relevant function returns backward slashes?

**Comment by MrSoup678** [comment] 2023-02-05 17:12
Yup CDirectoryItem::GetPath() returns platform dependant platform separators.

**Comment by FlaminSarge** [comment] 2023-02-06 12:47
> Yup CDirectoryItem::GetPath() returns platform dependant platform separators.

If you use Find() with backslashes in Linux does it break, or succeed? Obv in Win it fails to find files, but I think that was in the `filter` part, not where GetPath was called.

**Comment by MrSoup678** [comment] 2023-02-06 13:08
Beacuse GetPath _never_ was called. What filter does,is filtering the existing list of items against a query. But what happens, if that same list was never initialized?

Additionally, What I refered to the platform dependent separators I mean that it returns backslashes on Windows, but forward slashes on Linux. And I never tested that on Windows. So you got me there.
Thankfully I have fixed those both errors in my local directory.

**Comment by MrSoup678** [comment] 2023-02-06 13:21
Pushed fixes for both:
https://github.com/SlawekNowy/vsif2vcd/commit/10fbff9f84fb452f4249c92c9ae256c2fdac6867

**Comment by mfaizsyahmi** [comment] 2023-03-28 17:06
any latest build? I don't want to compile, I just want to pose.

**Comment by SuperMario20** [comment] 2023-05-11 07:12
> any latest build? I don't want to compile, I just want to pose.

hey, just posted my own compile from the latest version of the code
[https://github.com/SuperMario20/vsif2vcd/releases/tag/1.0.1](https://github.com/SuperMario20/vsif2vcd/releases/tag/1.0.1)

Edit: there's an official release now, no need to go to that url!

**Comment by FlaminSarge** [comment] 2023-05-19 03:45
Heads up that the above link's destination doesn't match its text.

**Comment by SuperMario20** [comment] 2023-05-19 23:51
> Heads up that the above link's destination doesn't match its text.

Now that there's an official release I think I'll just edit it out of the message but thanks for letting me know!

**Closed as completed** 2023-08-12 11:26 UTC
Labels: bug, regression
